version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    ports:
      - "27018:27017"

  redis:
    image: redis
    ports:
      - "6378:6379"


